// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIw7DyOBExSIiNWJ2PHedMSB1J4j0xqCA',
    appId: '1:152856632849:web:5af8e47ae9cbca5cec9bb0',
    messagingSenderId: '152856632849',
    projectId: 'puzzlepause-fe548',
    authDomain: 'puzzlepause-fe548.firebaseapp.com',
    storageBucket: 'puzzlepause-fe548.appspot.com',
    measurementId: 'G-7G4MREVM8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD--Nq-dL76eo5Ogopx0T3S3YHbsp10dtc',
    appId: '1:152856632849:android:b33dd63605143731ec9bb0',
    messagingSenderId: '152856632849',
    projectId: 'puzzlepause-fe548',
    storageBucket: 'puzzlepause-fe548.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9aWbsIiDPjxQj1tvcyL2164p1d5i9djQ',
    appId: '1:152856632849:ios:eb1f76830d2d17c9ec9bb0',
    messagingSenderId: '152856632849',
    projectId: 'puzzlepause-fe548',
    storageBucket: 'puzzlepause-fe548.appspot.com',
    androidClientId: '152856632849-glsksgnc7ji0m7cnin6qqn297999vmaq.apps.googleusercontent.com',
    iosClientId: '152856632849-rn3vrtn602kvo7jaur8bm3iauhm5k4jo.apps.googleusercontent.com',
    iosBundleId: 'com.example.puzzelpause',
  );
}
